// Tell Jenkins how to build projects from this repository
pipeline {
	
	agent {
		label 'magicdraw'
	}
	
	// Keep only the last 5 builds
	options {
		buildDiscarder(logRotator(numToKeepStr: '5'))
	}
	
	tools { 
		maven 'Maven 3.3.9' 
		jdk 'Oracle JDK 8' 
	}

	stages { 
		stage('Build Plug-in') { 
			steps {
				sh 'rm -rf build/dependency-cache'
				sh './gradlew clean'
				sh './gradlew build publish --refresh-dependencies'
			}
		}
		stage('Packaging') {
			steps{
				sh './package.sh'
			}
		}

	}

	post {
		always {
			archiveArtifacts artifacts: 'com.incquerylabs.magicdraw.plugin.example/build/distributions/com.incquerylabs.magicdraw.plugin.example-*.zip', onlyIfSuccessful: true
			archiveArtifacts artifacts: 'md_skeleton-*.zip', onlyIfSuccessful: true
			archiveArtifacts artifacts: 'com.incquerylabs.magicdraw.plugin.example/out.map', onlyIfSuccessful: true
		}
	}
}